import { useEffect, useState } from "react";
import { getClientPolicy, updateClientLimits, updateClientEndpoint, testClientEndpoint, getScheduleConfiguration, getScheduleTemplates, updateScheduleConfiguration, previewScheduleTemplate, applyScheduleTemplate, type ClientPolicy, type ScheduleConfiguration, type ScheduleTemplate, type ScheduleWeek } from "../../api";
import "./admin.css";
import { notify } from "../../state/feedback";

export function ClientPolicyPage() {
  const [policy, setPolicy] = useState<ClientPolicy | null>(null), [error, setError] = useState(""), [busy, setBusy] = useState(true), [revision, setRevision] = useState(0);
  const [message, setMessage] = useState("");
  useEffect(() => { let active = true; const controller = new AbortController(); setBusy(true); setError(""); getClientPolicy(controller.signal).then(value => { if (active) setPolicy(value); }).catch(reason => { if (active) setError(reason.message || "加载失败"); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; controller.abort(); }; }, [revision]);
  const run = async (action: () => Promise<ClientPolicy | string>) => { if (busy) return; setBusy(true); setMessage(""); try { const result = await action(); if (typeof result === "string") setMessage(result); else { setPolicy(result); setMessage("已保存"); } } catch (reason) { const text = reason instanceof Error ? reason.message : "操作失败"; setMessage(text); notify("error", text); } finally { setBusy(false); } };
  if (error) return <div role="alert">{error}<button className="secondary" onClick={() => setRevision(value => value + 1)}>重试</button></div>;
  if (!policy) return <div className="loading-line">正在加载数据访问控制</div>;
  return <section aria-label="数据访问控制"><header className="admin-feature-heading"><h3>数据访问控制</h3><button className="secondary" disabled={busy} onClick={() => setRevision(value => value + 1)}>刷新</button></header>
    <div className="admin-settings-section"><h3>返回数量</h3><div className="admin-settings-fields">{([["vehicleResultLimit", "车辆档案"], ["workOrderResultLimit", "微信车单"], ["wechatMessageResultLimit", "微信聊天记录"]] as const).map(([key, label]) => <label key={key}>{label}<input type="number" min={0} max={50} value={policy[key] ?? 0} disabled={busy} onChange={event => setPolicy({ ...policy, [key]: Number(event.target.value) })} /></label>)}</div><div className="admin-settings-actions"><button className="primary" disabled={busy} onClick={() => void run(async () => { const limits = { vehicleResultLimit: policy.vehicleResultLimit, workOrderResultLimit: policy.workOrderResultLimit, wechatMessageResultLimit: policy.wechatMessageResultLimit }; if (Object.values(limits).some(value => !Number.isInteger(value) || value < 0 || value > 50)) throw new Error("返回数量须为0至50的整数"); return updateClientLimits(limits); })}>保存数量</button></div></div>
    {(["api", "update"] as const).map(kind => { const key = kind === "api" ? "apiBaseUrl" : "updateBaseUrl", title = kind === "api" ? "服务地址" : "升级地址"; return <div className="admin-settings-section" key={kind}><div className="admin-settings-fields"><label>{title}<input type="url" value={policy[key] || ""} disabled={busy} onChange={event => setPolicy({ ...policy, [key]: event.target.value })} /></label></div><div className="admin-settings-actions"><button className="secondary" disabled={busy} onClick={() => void run(async () => { const result = await testClientEndpoint(kind, policy[key]); return result.message || (result.success ? "连接正常" : "连接失败"); })}>测试连接</button><button className="primary" disabled={busy} onClick={() => { if (window.confirm(`确认更改${title}？`)) void run(() => updateClientEndpoint(kind, policy[key])); }}>保存{title}</button></div></div>; })}
    <div className="admin-settings-section"><h3>客户端确认</h3><p>版本 {policy.revision ?? 0} · 已应用 {policy.appliedClientCount ?? 0} / {policy.clientCount ?? 0}</p></div>{message && <div className="admin-settings-message" role="status">{message}</div>}
  </section>;
}

const shiftLabels: Record<string, string> = { MORNING: "早班", AFTERNOON: "午班", SMALL_NIGHT: "小夜班", NIGHT: "夜班", OFF: "休息" };
export function SchedulePlanningPage() {
  const [configuration, setConfiguration] = useState<ScheduleConfiguration | null>(null), [templates, setTemplates] = useState<ScheduleTemplate[]>([]), [busy, setBusy] = useState(true), [error, setError] = useState(""), [message, setMessage] = useState(""), [revision, setRevision] = useState(0);
  const [selected, setSelected] = useState<number[]>([]), [cycle, setCycle] = useState(7), [date, setDate] = useState(() => new Intl.DateTimeFormat("sv-SE", { timeZone: "Asia/Shanghai" }).format(new Date())), [until, setUntil] = useState("");
  const [preview, setPreview] = useState<ScheduleWeek | null>(null);
  useEffect(() => { let active = true; const controller = new AbortController(); setBusy(true); setError(""); Promise.all([getScheduleConfiguration(controller.signal), getScheduleTemplates(controller.signal)]).then(([config, list]) => { if (active) { setConfiguration(config); setCycle(config.cycleDays); setSelected((config.participants || []).map(item => item.id)); setTemplates(list.items || []); } }).catch(reason => { if (active) { setError(reason.message || "加载失败"); controller.abort(); } }).finally(() => { if (active) setBusy(false); }); return () => { active = false; controller.abort(); }; }, [revision]);
  const run = async (action: () => Promise<void>) => { if (busy) return; setBusy(true); setMessage(""); try { await action(); } catch (reason) { const text = reason instanceof Error ? reason.message : "操作失败"; setMessage(text); notify("error", text); } finally { setBusy(false); } };
  if (error) return <div role="alert">{error}<button className="secondary" onClick={() => setRevision(value => value + 1)}>重试</button></div>;
  if (!configuration) return <div className="loading-line">正在加载排班规划</div>;
  return <section aria-label="排班规划"><header className="admin-feature-heading"><h3>排班规划</h3><button className="secondary" disabled={busy} onClick={() => setRevision(value => value + 1)}>刷新</button></header><div className="admin-settings-section"><div className="admin-settings-fields"><label>轮班周期<input type="number" min={1} max={15} value={cycle} disabled={busy} onChange={event => setCycle(Number(event.target.value))} /></label></div><h3>排班人员</h3><div className="permission-checks">{[...new Map([...(configuration.candidates || []), ...(configuration.participants || [])].map(item => [item.id, item])).values()].map(item => <label key={item.id}><input type="checkbox" checked={selected.includes(item.id)} disabled={busy || (item.status !== "ACTIVE" && !selected.includes(item.id))} onChange={event => setSelected(event.target.checked ? [...selected, item.id] : selected.filter(id => id !== item.id))} />{item.realName || item.username}</label>)}</div><div className="admin-settings-actions"><button className="primary" disabled={busy} onClick={() => void run(async () => { if (!Number.isInteger(cycle) || cycle < 1 || cycle > 15) throw new Error("轮班周期须为1至15天"); const next = await updateScheduleConfiguration(cycle, selected); setConfiguration(next); setSelected(next.participants.map(item => item.id)); setMessage("排班配置已保存"); })}>保存排班配置</button></div></div>
    <div className="admin-settings-section"><h3>排班模板</h3><div className="admin-settings-fields"><label>生效日期<input type="date" value={date} disabled={busy} onChange={event => { setDate(event.target.value); setPreview(null); }} /></label><label>结束日期<input type="date" value={until} min={date} disabled={busy} onChange={event => setUntil(event.target.value)} /></label></div>{templates.map(template => <div className="admin-template-row" key={template.id}><strong>{template.name}</strong><p>{template.cycleDays} 天 · 版本 {template.versionNumber}</p><div className="admin-settings-actions"><button className="secondary" disabled={busy || !date} onClick={() => void run(async () => { setPreview(await previewScheduleTemplate(template.id, date)); })}>预览 {template.name}</button><button className="primary" disabled={busy || !date} onClick={() => { if (window.confirm(`确认应用排班模板“${template.name}”？`)) void run(async () => { if (until && until < date) throw new Error("结束日期不能早于生效日期"); await applyScheduleTemplate(template.id, date, until || null); setMessage("模板已应用"); setRevision(value => value + 1); }); }}>应用 {template.name}</button></div></div>)}{!templates.length && <div className="empty-state compact"><h3>暂无排班模板</h3></div>}</div>
    {preview && <div className="admin-settings-section"><h3>排班预览</h3>{preview.shifts.map((shift, index) => <p key={index}>{shift.date} · {shiftLabels[shift.shiftType] || "班次"} · {shift.persons.map(person => person.realName || person.username).join("、")}</p>)}</div>}{message && <div className="admin-settings-message" role="status">{message}</div>}
  </section>;
}
