ALTER TABLE users
    ADD COLUMN avatar_content BYTEA,
    ADD COLUMN avatar_content_type VARCHAR(64),
    ADD COLUMN avatar_version BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN auth_version BIGINT NOT NULL DEFAULT 0;

CREATE TABLE vehicle_query_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT NOT NULL,
    vehicle_id BIGINT NOT NULL,
    category VARCHAR(40) NOT NULL,
    vehicle_type VARCHAR(128),
    queried_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vehicle_query_events_actor FOREIGN KEY (actor_id) REFERENCES users (id),
    CONSTRAINT fk_vehicle_query_events_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE
);

CREATE INDEX idx_vehicle_query_events_actor_time
    ON vehicle_query_events (actor_id, queried_at DESC);

CREATE INDEX idx_vehicle_query_events_category_time
    ON vehicle_query_events (category, queried_at DESC);

CREATE INDEX idx_vehicle_query_events_vehicle_type_time
    ON vehicle_query_events (vehicle_type, queried_at DESC);
