CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT uq_users_username UNIQUE (username),
    CONSTRAINT ck_users_role CHECK (role IN ('ADMIN', 'USER')),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'DISABLED')),
    CONSTRAINT fk_users_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_users_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
);

CREATE TABLE import_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file_name VARCHAR(255) NOT NULL,
    source_checksum VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    total_rows INTEGER NOT NULL DEFAULT 0,
    valid_rows INTEGER NOT NULL DEFAULT 0,
    duplicate_rows INTEGER NOT NULL DEFAULT 0,
    error_rows INTEGER NOT NULL DEFAULT 0,
    published_at TIMESTAMPTZ,
    published_by BIGINT,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT ck_import_batches_status CHECK (status IN ('DRAFT', 'VALIDATED', 'PUBLISHED', 'ROLLED_BACK', 'FAILED')),
    CONSTRAINT fk_import_batches_published_by FOREIGN KEY (published_by) REFERENCES users (id),
    CONSTRAINT fk_import_batches_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_import_batches_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
);

CREATE TABLE vehicles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number VARCHAR(32) NOT NULL,
    normalized_plate VARCHAR(32) NOT NULL,
    category VARCHAR(40) NOT NULL,
    vehicle_type VARCHAR(128),
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    import_batch_id BIGINT,
    attributes JSONB NOT NULL DEFAULT '{}'::JSONB,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT ck_vehicles_category CHECK (category IN ('RESIDENT', 'SCENIC_UNIT', 'SCENIC_ENTERPRISE', 'CADRE', 'KANAS_TOURISM_DEVELOPMENT')),
    CONSTRAINT ck_vehicles_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT fk_vehicles_import_batch FOREIGN KEY (import_batch_id) REFERENCES import_batches (id),
    CONSTRAINT fk_vehicles_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_vehicles_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
);

CREATE UNIQUE INDEX uq_vehicles_active_normalized_plate
    ON vehicles (normalized_plate)
    WHERE status = 'ACTIVE';

CREATE INDEX idx_vehicles_normalized_plate_trgm
    ON vehicles USING GIN (normalized_plate gin_trgm_ops);

CREATE TABLE resident_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    owner_name VARCHAR(128) NOT NULL,
    identity_card_number VARCHAR(32) NOT NULL,
    contact_phone VARCHAR(32),
    remarks TEXT,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT uq_resident_profiles_vehicle UNIQUE (vehicle_id),
    CONSTRAINT fk_resident_profiles_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE,
    CONSTRAINT fk_resident_profiles_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_resident_profiles_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
);

CREATE TABLE long_term_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id BIGINT NOT NULL,
    organization_name VARCHAR(255),
    pass_holder VARCHAR(255),
    passage_details TEXT,
    remarks TEXT,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT uq_long_term_profiles_vehicle UNIQUE (vehicle_id),
    CONSTRAINT fk_long_term_profiles_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE CASCADE,
    CONSTRAINT fk_long_term_profiles_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_long_term_profiles_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
);

CREATE TABLE import_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id BIGINT NOT NULL,
    source_sheet_name VARCHAR(255) NOT NULL,
    source_row_number INTEGER NOT NULL,
    raw_values JSONB NOT NULL DEFAULT '{}'::JSONB,
    parsed_values JSONB NOT NULL DEFAULT '{}'::JSONB,
    result_status VARCHAR(16) NOT NULL,
    error_message TEXT,
    vehicle_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT ck_import_rows_result_status CHECK (result_status IN ('VALID', 'DUPLICATE', 'ERROR', 'PUBLISHED')),
    CONSTRAINT uq_import_rows_source UNIQUE (import_batch_id, source_sheet_name, source_row_number),
    CONSTRAINT fk_import_rows_batch FOREIGN KEY (import_batch_id) REFERENCES import_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_import_rows_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles (id),
    CONSTRAINT fk_import_rows_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_import_rows_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT,
    action_type VARCHAR(64) NOT NULL,
    target_type VARCHAR(64) NOT NULL,
    target_id BIGINT,
    result_status VARCHAR(16) NOT NULL,
    request_id VARCHAR(64),
    metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_audit_logs_result_status CHECK (result_status IN ('SUCCESS', 'FAILURE', 'DENIED')),
    CONSTRAINT fk_audit_logs_actor FOREIGN KEY (actor_id) REFERENCES users (id)
);

CREATE INDEX idx_audit_logs_actor_created_at ON audit_logs (actor_id, created_at DESC);
CREATE INDEX idx_audit_logs_target_created_at ON audit_logs (target_type, target_id, created_at DESC);

CREATE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_import_batches_updated_at
    BEFORE UPDATE ON import_batches
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_vehicles_updated_at
    BEFORE UPDATE ON vehicles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_resident_profiles_updated_at
    BEFORE UPDATE ON resident_profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_long_term_profiles_updated_at
    BEFORE UPDATE ON long_term_profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_import_rows_updated_at
    BEFORE UPDATE ON import_rows
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
