ALTER TABLE users ADD COLUMN real_name VARCHAR(64);

UPDATE users SET real_name = CASE id
    WHEN 3 THEN '刘添'
    WHEN 4 THEN '许志川'
    WHEN 5 THEN '穆拉迪力'
    WHEN 6 THEN '张默涵'
    WHEN 7 THEN '孙成航'
    WHEN 8 THEN '易杰'
    WHEN 9 THEN '徐如军'
    WHEN 10 THEN '加依桑'
    WHEN 11 THEN '艾力'
    WHEN 12 THEN '达吾提'
END
WHERE id BETWEEN 3 AND 12;

CREATE TABLE schedule_participants (
    account_id BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schedule_participants (account_id)
SELECT id FROM users WHERE id IN (3, 4, 5, 6, 7, 8, 10, 11, 12)
ON CONFLICT DO NOTHING;

CREATE TABLE schedule_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    archived_at TIMESTAMPTZ,
    created_by BIGINT NOT NULL REFERENCES users (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE schedule_template_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES schedule_templates (id) ON DELETE RESTRICT,
    version_number INTEGER NOT NULL,
    cycle_days SMALLINT NOT NULL,
    created_by BIGINT NOT NULL REFERENCES users (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_schedule_template_versions UNIQUE (template_id, version_number),
    CONSTRAINT ck_schedule_template_cycle_days CHECK (cycle_days BETWEEN 1 AND 9)
);

CREATE TABLE schedule_shift_assignments (
    template_version_id BIGINT NOT NULL REFERENCES schedule_template_versions (id) ON DELETE CASCADE,
    cycle_day SMALLINT NOT NULL,
    shift_type VARCHAR(16) NOT NULL,
    account_id BIGINT NOT NULL REFERENCES schedule_participants (account_id) ON DELETE RESTRICT,
    PRIMARY KEY (template_version_id, cycle_day, shift_type, account_id),
    CONSTRAINT ck_schedule_assignment_day CHECK (cycle_day BETWEEN 1 AND 9),
    CONSTRAINT ck_schedule_assignment_shift CHECK (shift_type IN ('MORNING', 'AFTERNOON', 'SMALL_NIGHT', 'NIGHT'))
);

CREATE TABLE schedule_applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_version_id BIGINT NOT NULL REFERENCES schedule_template_versions (id) ON DELETE RESTRICT,
    effective_from DATE NOT NULL UNIQUE,
    applied_by BIGINT NOT NULL REFERENCES users (id),
    applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_schedule_applications_effective_from ON schedule_applications (effective_from DESC);
CREATE INDEX idx_schedule_assignments_version_day ON schedule_shift_assignments (template_version_id, cycle_day);

CREATE TRIGGER trg_schedule_templates_updated_at
    BEFORE UPDATE ON schedule_templates
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
