ALTER TABLE users
    ADD COLUMN wechat_work_order_access_enabled BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE users
SET wechat_work_order_access_enabled = TRUE
WHERE username = 'admin' AND role = 'ADMIN';

CREATE TABLE wechat_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key VARCHAR(128) NOT NULL UNIQUE,
    display_name VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    collector_status VARCHAR(32) NOT NULL DEFAULT 'OFFLINE',
    latest_message_at TIMESTAMPTZ,
    last_heartbeat_at TIMESTAMPTZ,
    last_uploaded_at TIMESTAMPTZ,
    backlog_count INTEGER NOT NULL DEFAULT 0,
    error_code VARCHAR(64),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_wechat_sources_status CHECK (collector_status IN ('OFFLINE', 'WECHAT_NOT_READY', 'CATCHING_UP', 'HEALTHY', 'KEY_MISSING', 'UPLOAD_FAILED'))
);

CREATE TABLE wechat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES wechat_sources(id),
    local_message_id VARCHAR(128) NOT NULL,
    sender_username VARCHAR(255),
    sender_display VARCHAR(255),
    sender_group_nickname VARCHAR(255),
    message_type VARCHAR(32) NOT NULL DEFAULT 'TEXT',
    raw_content TEXT NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL,
    content_fingerprint VARCHAR(64) NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_wechat_messages_source_local UNIQUE (source_id, local_message_id),
    CONSTRAINT ck_wechat_messages_type CHECK (message_type IN ('TEXT', 'IMAGE_METADATA'))
);

CREATE INDEX idx_wechat_messages_source_sent ON wechat_messages(source_id, sent_at DESC, id DESC);

CREATE TABLE work_order_catalog_state (
    id INTEGER PRIMARY KEY,
    revision BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_work_order_catalog_singleton CHECK (id = 1)
);

INSERT INTO work_order_catalog_state(id, revision) VALUES (1, 0);

CREATE TABLE work_order_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL UNIQUE REFERENCES wechat_messages(id) ON DELETE CASCADE,
    order_number VARCHAR(128),
    raw_plate VARCHAR(255),
    normalized_plate VARCHAR(255),
    vehicle_type VARCHAR(255),
    declared_people INTEGER,
    raw_valid_time VARCHAR(255),
    location TEXT,
    verification_method TEXT,
    reason TEXT,
    remarks TEXT,
    status VARCHAR(24) NOT NULL DEFAULT 'ACTIVE',
    parse_quality VARCHAR(24) NOT NULL,
    searchable_text TEXT NOT NULL,
    catalog_revision BIGINT NOT NULL,
    parsed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_work_order_status CHECK (status IN ('ACTIVE', 'VOID')),
    CONSTRAINT ck_work_order_parse_quality CHECK (parse_quality IN ('COMPLETE', 'PARTIAL', 'RAW_FALLBACK'))
);

CREATE INDEX idx_work_order_order_number ON work_order_records(order_number);
CREATE INDEX idx_work_order_normalized_plate ON work_order_records(normalized_plate);
CREATE INDEX idx_work_order_catalog_revision ON work_order_records(catalog_revision);
CREATE INDEX idx_work_order_search_trgm ON work_order_records USING GIN(searchable_text gin_trgm_ops);

CREATE TABLE work_order_people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_id BIGINT NOT NULL REFERENCES work_order_records(id) ON DELETE CASCADE,
    sequence_number INTEGER NOT NULL,
    raw_line TEXT NOT NULL,
    person_name VARCHAR(255),
    identity_number VARCHAR(64),
    CONSTRAINT uq_work_order_people_sequence UNIQUE(record_id, sequence_number)
);

CREATE TABLE work_order_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES wechat_sources(id),
    local_attachment_id VARCHAR(255) NOT NULL,
    sender_username VARCHAR(255),
    sender_display VARCHAR(255),
    sent_at TIMESTAMPTZ NOT NULL,
    sha256 VARCHAR(64),
    original_content_type VARCHAR(128),
    original_size BIGINT,
    original_path TEXT,
    preview_path TEXT,
    preview_size BIGINT,
    thumbnail_path TEXT,
    thumbnail_size BIGINT,
    availability VARCHAR(32) NOT NULL DEFAULT 'METADATA_ONLY',
    linked_record_id BIGINT REFERENCES work_order_records(id) ON DELETE SET NULL,
    association_method VARCHAR(16),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_work_order_images_source_local UNIQUE(source_id, local_attachment_id),
    CONSTRAINT ck_work_order_images_availability CHECK (availability IN ('METADATA_ONLY', 'AVAILABLE', 'UNAVAILABLE')),
    CONSTRAINT ck_work_order_images_association CHECK (association_method IS NULL OR association_method IN ('AUTO', 'MANUAL'))
);

CREATE INDEX idx_work_order_images_record ON work_order_images(linked_record_id, sent_at, id);
CREATE INDEX idx_work_order_images_source_sent ON work_order_images(source_id, sent_at, id);

CREATE TRIGGER trg_wechat_sources_updated_at
    BEFORE UPDATE ON wechat_sources
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trg_work_order_images_updated_at
    BEFORE UPDATE ON work_order_images
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
