CREATE TABLE wechat_sync_runs (
    sync_run_id UUID PRIMARY KEY,
    collector_instance_id VARCHAR(128) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMPTZ,
    status VARCHAR(24) NOT NULL DEFAULT 'RUNNING',
    error_code VARCHAR(64),
    CONSTRAINT ck_wechat_sync_runs_status CHECK (status IN ('RUNNING', 'COMPLETED', 'FAILED'))
);

CREATE TABLE wechat_sync_batches (
    batch_id UUID PRIMARY KEY,
    sync_run_id UUID NOT NULL REFERENCES wechat_sync_runs(sync_run_id),
    source_id BIGINT NOT NULL REFERENCES wechat_sources(id),
    from_timestamp BIGINT NOT NULL,
    from_local_message_id VARCHAR(128) NOT NULL DEFAULT '',
    to_timestamp BIGINT NOT NULL,
    to_local_message_id VARCHAR(128) NOT NULL,
    message_count INTEGER NOT NULL,
    batch_sha256 VARCHAR(64) NOT NULL,
    accepted_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(32) NOT NULL DEFAULT 'RECEIVING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMPTZ,
    CONSTRAINT ck_wechat_sync_batches_status CHECK (status IN ('RECEIVING', 'ACCEPTED', 'REJECTED', 'RECONCILE_REQUIRED')),
    CONSTRAINT ck_wechat_sync_batches_count CHECK (message_count > 0 AND accepted_count >= 0)
);
CREATE INDEX idx_wechat_sync_batches_source_created ON wechat_sync_batches(source_id, created_at DESC);
CREATE INDEX idx_wechat_sync_batches_run ON wechat_sync_batches(sync_run_id);

CREATE TABLE wechat_sync_watermarks (
    source_id BIGINT PRIMARY KEY REFERENCES wechat_sources(id),
    accepted_timestamp BIGINT NOT NULL DEFAULT 0,
    accepted_local_message_id VARCHAR(128) NOT NULL DEFAULT '',
    accepted_message_count BIGINT NOT NULL DEFAULT 0,
    last_batch_id UUID REFERENCES wechat_sync_batches(batch_id),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE wechat_attachment_upload_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL REFERENCES wechat_sources(id),
    local_attachment_id VARCHAR(255) NOT NULL,
    local_message_id VARCHAR(128),
    attachment_kind VARCHAR(16) NOT NULL,
    file_name TEXT,
    local_locator TEXT,
    source_quality VARCHAR(24) NOT NULL DEFAULT 'UNKNOWN',
    original_size BIGINT,
    sha256 VARCHAR(64),
    uploaded_bytes BIGINT NOT NULL DEFAULT 0,
    status VARCHAR(24) NOT NULL DEFAULT 'DISCOVERED',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ,
    last_error_code VARCHAR(64),
    last_error_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_wechat_attachment_upload_task UNIQUE(source_id, local_attachment_id),
    CONSTRAINT ck_wechat_attachment_upload_task_status CHECK (status IN ('DISCOVERED', 'WAITING_SOURCE', 'METADATA_ONLY', 'WAITING_UPLOAD', 'UPLOADING', 'RETRY_WAIT', 'UPLOADED', 'VERIFYING', 'FAILED'))
);
CREATE INDEX idx_wechat_attachment_upload_task_retry ON wechat_attachment_upload_tasks(status, next_retry_at);
