ALTER TABLE import_rows
    ADD COLUMN source_item_index INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN planned_action VARCHAR(16) NOT NULL DEFAULT 'NONE';

ALTER TABLE import_rows
    DROP CONSTRAINT uq_import_rows_source;

ALTER TABLE import_rows
    ADD CONSTRAINT uq_import_rows_source_item
    UNIQUE (import_batch_id, source_sheet_name, source_row_number, source_item_index);

ALTER TABLE import_rows
    ADD CONSTRAINT ck_import_rows_planned_action
    CHECK (planned_action IN ('CREATE', 'UPDATE', 'SKIP', 'NONE'));

CREATE TABLE import_effects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_batch_id BIGINT NOT NULL,
    import_row_id BIGINT NOT NULL,
    vehicle_id BIGINT,
    action VARCHAR(16) NOT NULL,
    applied_version INTEGER NOT NULL,
    previous_vehicle JSONB,
    previous_resident_profile JSONB,
    previous_long_term_profile JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_import_effects_row UNIQUE (import_row_id),
    CONSTRAINT ck_import_effects_action CHECK (action IN ('CREATED', 'UPDATED')),
    CONSTRAINT fk_import_effects_batch
        FOREIGN KEY (import_batch_id) REFERENCES import_batches (id) ON DELETE CASCADE,
    CONSTRAINT fk_import_effects_row
        FOREIGN KEY (import_row_id) REFERENCES import_rows (id) ON DELETE CASCADE,
    CONSTRAINT fk_import_effects_vehicle
        FOREIGN KEY (vehicle_id) REFERENCES vehicles (id) ON DELETE SET NULL
);

CREATE INDEX idx_import_effects_batch ON import_effects (import_batch_id, id);
