ktor {
  deployment {
    port = ${?PORT}
    port = 8080
  }
  application {
    modules = [ com.jaydocoder.plateview.server.ApplicationKt.module ]
  }
}

database {
  jdbcUrl = ${?DATABASE_URL}
  username = ${?DATABASE_USERNAME}
  password = ${?DATABASE_PASSWORD}
  migrateOnStart = ${?DATABASE_MIGRATE_ON_START}
  migrateOnStart = true
}
