import { useEffect, useState, type ReactNode } from "react";
import type { VehicleDetail, WechatMessage, WorkOrder } from "../../api";
import { downloadAttachment } from "../../api";
import { adaptAttachments, type AttachmentInfo } from "../../adapters";
import { ArrowLeft, ChevronRight, FileText, Image as ImageIcon } from "../../components/icons";

const categoryLabels: Record<string, string> = { RESIDENT: "村民车辆", OTHER_LONG_TERM: "其他长期车辆", SCENIC_UNIT: "驻景区单位", SCENIC_ENTERPRISE: "驻景区企业", CADRE: "干部车辆", KANAS_TOURISM_DEVELOPMENT: "喀旅公司" };

export function VehicleDetailPage({ detail, onBack }: { detail: VehicleDetail; onBack: () => void }) {
  const fields = (value: Record<string, unknown>, map: Array<[string, string]>) => map.filter(([, key]) => hasDetailValue(value[key])).map(([label, key]) => [label, String(value[key])] as [string, string]);
  const resident = fields((detail.residentProfile || {}) as Record<string, unknown>, [["车主姓名", "ownerName"], ["身份证号", "identityCardNumber"], ["联系电话", "contactPhone"], ["村民备注", "remarks"]]);
  const longTerm = fields((detail.longTermProfile || {}) as Record<string, unknown>, [["单位名称", "organizationName"], ["通行人员", "passHolder"], ["通行信息", "passageDetails"], ["备注", "remarks"]]);
  const attributesMap = (detail.attributes || {}) as Record<string, unknown>;
  const attributes = Object.entries(attributesMap).filter(([key, value]) => key !== "plateColor" && key !== "车牌颜色" && hasDetailValue(value)).map(([key, value]) => [attributeLabel(key), String(value)] as [string, string]);
  const vehicleFields = [hasDetailValue(detail.vehicleType) ? ["车辆类型", String(detail.vehicleType)] as [string, string] : null, ...attributes].filter((item): item is [string, string] => item !== null);
  const plateColor = detail.plateColor || attributesMap.plateColor || attributesMap["车牌颜色"];
  const category = String(detail.category || "");
  return <section className="page detail-page"><button className="back-button" onClick={onBack}><ArrowLeft size={16} />车辆详情</button><div className="vehicle-detail-cover"><div className="vehicle-detail-overlay"><PlateBadge plate={String(detail.plateNumber || "未知车牌")} color={plateColor} /><strong className={`vehicle-category ${categoryTone(category)}`}>{String(detail.categoryLabel || categoryLabels[category] || "车辆档案")}</strong><VehicleStatus status={String(detail.status || "ACTIVE")} /></div></div>{detail.status !== "ACTIVE" && <div className={`risk-banner ${String(detail.status).toLowerCase()}`}><VehicleStatus status={String(detail.status)} /><span>{String(detail.status) === "STRICT_CHECK" ? "该车辆需严查后再放行" : String(detail.status) === "BLACKLISTED" ? "该车辆档案已被管理员拉黑" : "该车辆档案当前不可直接放行"}</span></div>}{resident.length > 0 && <DetailGroup title="村民核验信息" fields={resident} />}{longTerm.length > 0 && <DetailGroup title="长期通行资料" fields={longTerm} />}{vehicleFields.length > 0 && <DetailGroup title="车辆信息" fields={vehicleFields} />}</section>;
}

export function WorkOrderDetailPage({ detail, onBack }: { detail: WorkOrder; onBack: () => void }) {
  const attachments = adaptAttachments(detail.attachments || detail.images);
  const passageState = workOrderPassageLabel(detail);
  const sourceFields = detailFields([
    ["微信群", detail.sourceName],
    ["发送者", detail.senderDisplay || detail.senderName || detail.senderGroupNickname || detail.senderUsername],
    ["发送时间", formatDate(detail.sentAt)],
  ]);
  const passageFields = detailFields([
    ["车牌", (detail.plateNumbers || []).join("、")],
    ["车型", detail.vehicleType],
    ["通行时间", detail.rawValidTime || detail.validTime],
    ["通行区域", detail.location],
    ["通行方式", detail.verificationMethod],
    ["人数", detail.declaredPeople],
  ]);
  const reasonFields = detailFields([["事由", detail.reason], ["备注", detail.remarks]]);
  const people = Array.isArray(detail.people) ? detail.people : [];
  const rawContent = hasDetailValue(detail.rawContent) ? String(detail.rawContent) : hasDetailValue(detail.title) ? String(detail.title) : "";
  const plates = Array.isArray(detail.plateNumbers) && detail.plateNumbers.length ? detail.plateNumbers : extractPlates(detail.rawContent);
  return <section className="page detail-page"><button className="back-button" onClick={onBack}><ArrowLeft size={16} />返回微信车单</button><div className="detail-hero workorder-hero workorder-cover"><img className="workorder-cover-image" src="/web/vehicle-detail-mountain-road.png" alt="" aria-hidden="true" /><div className="workorder-cover-content"><span className="category-label">微信车单 · {detail.orderYear || "未知年份"}</span><h2>{detail.orderNumber || "未识别单号"}</h2>{plates.length > 0 && <div className="plate-list detail-hero-plates">{plates.map(plate => <PlateBadge key={plate} plate={plate} color="BLUE" />)}</div>}<p>{detail.sourceName || "微信来源"} · {formatDate(detail.sentAt)}</p></div><Status status={passageState} /></div>{rawContent && <DetailGroup title="微信原始内容" content={rawContent} />}{sourceFields.length > 0 && <DetailGroup title="微信来源" fields={sourceFields} />}{passageFields.length > 0 && <DetailGroup title="通行信息" fields={passageFields} />}{people.length > 0 && <DetailGroup title="人员信息" fields={people.map((person: unknown, index) => { const value = person as Record<string, unknown>; return [String(value.name || value.realName || `人员 ${index + 1}`), String(value.phone || value.identityNumber || value.identityCardNumber || value.rawLine || "")] as [string, string]; }).filter(([, value]) => hasDetailValue(value))} />}{reasonFields.length > 0 && <DetailGroup title="事由与备注" fields={reasonFields} />}{attachments.length > 0 && <AttachmentGroup items={attachments} />}</section>;
}

export function WechatMessageDetailPage({ detail, onBack }: { detail: WechatMessage; onBack: () => void }) { const attachments = adaptAttachments(detail.attachments || detail.images); const status = String(detail.passageState || detail.status || ""); const sender = String(detail.displayName || detail.senderDisplay || detail.senderGroupNickname || "微信消息"); const plates = detail.plateNumbers?.length ? detail.plateNumbers : extractPlates(detail.rawContent); const sourceFields = detailFields([["发送者", sender], ["微信群", detail.sourceName], ["发送时间", formatDate(detail.sentAt)]]); return <section className="page detail-page"><button className="back-button" onClick={onBack}><ArrowLeft size={16} />返回聊天记录</button><div className={`detail-hero message-hero ${isLeaderSender(detail) ? "leader-result" : ""}`}><div><span className="category-label">微信聊天记录</span><h2 className={isLeaderSender(detail) ? "leader-sender" : ""}>{sender}</h2><p>{detail.sourceName || "微信来源"} · {formatDate(detail.sentAt)}</p></div>{status && <Status status={status} />}</div><DetailGroup title="微信原始内容" content={detail.rawContent || "暂无正文"} />{sourceFields.length > 0 && <DetailGroup title="微信来源" fields={sourceFields} />}{plates.length > 0 ? <DetailGroup title="识别到的车牌" fields={[["全部车牌", plates.join("、")]]} /> : null}{status && <DetailGroup title="通行状态" fields={[["状态", statusLabel(status)]]} />}{attachments.length > 0 && <AttachmentGroup items={attachments} />}</section>; }

function DetailGroup({ title, fields, content, children }: { title: string; fields?: Array<[string, string]>; content?: string; children?: ReactNode }) { return <section className="detail-section"><div className="section-title"><h3>{title}</h3></div>{content !== undefined && content !== "" ? <div className="long-content">{content}</div> : children || <div className="detail-fields">{fields?.map(([label, value]) => <div className="detail-field" key={label}><span>{label}</span><strong>{value || "—"}</strong></div>)}</div>}</section>; }
function AttachmentGroup({ items }: { items: AttachmentInfo[] }) { return <DetailGroup title="相关附件" content=""><div />{items.map((item, index) => <AttachmentRow key={String(item.id || index)} item={item} index={index} />)}</DetailGroup>; }
function AttachmentRow({ item, index }: { item: AttachmentInfo; index: number }) { const [state, setState] = useState("idle"); const [url, setUrl] = useState<string | null>(null); useEffect(() => () => { if (url) URL.revokeObjectURL(url); }, [url]); const open = async () => { if (url) { window.open(url, "_blank", "noopener,noreferrer"); return; } if (!item.id) return; setState("loading"); try { const blob = await downloadAttachment(item.id, item.kind === "PDF" ? "original" : "preview"); const next = URL.createObjectURL(blob); setUrl(next); window.open(next, "_blank", "noopener,noreferrer"); setState("ready"); } catch { setState("failed"); } }; return <button className="attachment-row" onClick={() => void open()}><span className={`attachment-icon ${item.kind === "PDF" ? "pdf" : "image"}`}>{item.kind === "PDF" ? <FileText size={16} /> : <ImageIcon size={16} />}</span><span><strong>{item.fileName || `附件 ${index + 1}`}</strong><small>{state === "loading" ? "正在加载附件" : state === "failed" ? "加载失败，点击重试" : item.status || item.availability || "点击预览"}</small></span><span className="chevron"><ChevronRight size={19} /></span></button>; }
function statusLabel(value: string) { return ({ ACTIVE: "正常通行", BLACKLISTED: "拉黑", STRICT_CHECK: "严查", INACTIVE: "已停用", VALID: "通行时间有效", OUTSIDE_ALLOWED_HOURS: "不在通行时间", AREA_MISMATCH: "通行区域不符", AREA_UNKNOWN: "通行区域未知", EXPIRED: "通行时间已过期", NOT_STARTED: "通行时间未开始", UNKNOWN: "通行时间待定" } as Record<string, string>)[value] || value; }
function statusTone(value: string) { const label = statusLabel(value); return /不符|不在|过期|已停用|拉黑|失效/.test(label) ? "abnormal" : /未知|待定|未开始/.test(label) ? "pending" : "active"; }
function Status({ status }: { status: string }) { return <span className={`status ${statusTone(status)}`}>{statusLabel(status)}</span>; }
function formatDate(value?: string | null) { if (!value) return "暂无记录"; const date = new Date(value); return Number.isNaN(date.getTime()) ? value : new Intl.DateTimeFormat("zh-CN", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Shanghai" }).format(date); }
function hasDetailValue(value: unknown): boolean { if (value === null || value === undefined) return false; const text = String(value).trim(); return text !== "" && !["未填写", "暂无", "暂无记录", "未知", "未知信息", "—", "-"].includes(text); }
function detailFields(entries: Array<[string, unknown]>): Array<[string, string]> { return entries.filter(([, value]) => hasDetailValue(value)).map(([label, value]) => [label, String(value)]); }
function attributeLabel(key: string) { return ({ vehicleUse: "车辆用途", passageArea: "通行区域", vehicleType: "车辆类型", plateColor: "车牌颜色", ownerName: "车主姓名", remarks: "备注", brandModel: "品牌型号", approvedCapacity: "核定载客数", approvedLoad: "核定载质量", vehicleColor: "车辆颜色", fuelType: "燃料类型", registrationDate: "登记日期", registrationNumber: "登记编号", department: "所属部门", usage: "使用用途", accessArea: "通行区域", accessTime: "通行时间" } as Record<string, string>)[key] || key; }
function categoryTone(category: string) { return ({ RESIDENT: "resident", SCENIC_UNIT: "scenic-unit", SCENIC_ENTERPRISE: "scenic-enterprise", KANAS_TOURISM_DEVELOPMENT: "kanas", CADRE: "cadre", OTHER_LONG_TERM: "long-term" } as Record<string, string>)[category] || "default"; }
function plateTone(color: unknown) { const value = String(color || "").toUpperCase(); if (/黄|YELLOW/.test(value)) return "yellow"; if (/绿|GREEN/.test(value)) return "green"; if (/白|WHITE/.test(value)) return "white"; if (/黑|BLACK/.test(value)) return "black"; return "blue"; }
function PlateBadge({ plate, color }: { plate: string; color?: unknown }) { return <span className={`plate-badge plate-${plateTone(color)}`}>{plate}</span>; }
function VehicleStatus({ status }: { status: string }) { const labels: Record<string, string> = { ACTIVE: "核验就绪", STRICT_CHECK: "严查", BLACKLISTED: "拉黑", INACTIVE: "已停用", DELETED: "已删除" }; const tone = status === "STRICT_CHECK" ? "warning" : status === "BLACKLISTED" || status === "INACTIVE" || status === "DELETED" ? "danger" : "ready"; return <span className={`vehicle-status ${tone}`}>{labels[status] || status}</span>; }
function extractPlates(value: unknown): string[] { const matches = String(value || "").match(/[京津沪渝冀豫云辽黑湘皖鲁苏浙赣鄂桂甘晋蒙陕吉闽贵粤青藏川宁琼新使领][A-HJ-NP-Z][A-HJ-NP-Z0-9]{5,6}/gi); return matches ? Array.from(new Set(matches)) : []; }
function isLeaderSender(detail: WechatMessage) { return detail.businessType === "PASSAGE_MESSAGE" || /徐站|徐如军|三叔/.test(String(detail.displayName || detail.senderDisplay || detail.senderGroupNickname || "")); }
function workOrderPassageLabel(item: WorkOrder): string { const explicit = String(item.passageState || item.passageStatus || ""); if (explicit) return explicit; if (item.status && item.status !== "ACTIVE") return String(item.status); if (!hasDetailValue(item.rawValidTime || item.validTime)) return "UNKNOWN"; if (!hasDetailValue(item.location)) return "AREA_UNKNOWN"; if (!String(item.location).includes("喀纳斯")) return "AREA_MISMATCH"; const raw = String(item.rawValidTime || item.validTime || ""); const match = raw.match(/(\d{1,2})[./-](\d{1,2})\s*[-~至](\d{1,2})[./-](\d{1,2})/); if (!match) return "UNKNOWN"; const now = new Date(); const year = Number(item.orderYear || now.getFullYear()); const end = new Date(year, Number(match[3]) - 1, Number(match[4]), 23, 59, 59); const start = new Date(year, Number(match[1]) - 1, Number(match[2])); if (now < start) return "NOT_STARTED"; if (now > end) return "EXPIRED"; const remark = String(item.remarks || ""); const time = remark.match(/(\d{1,2}):(\d{2})\s*[-~至](\d{1,2}):(\d{2})/); if (time) { const minutes = now.getHours() * 60 + now.getMinutes(); const from = Number(time[1]) * 60 + Number(time[2]); const to = Number(time[3]) * 60 + Number(time[4]); if (minutes < from || minutes > to) return "OUTSIDE_ALLOWED_HOURS"; } return "VALID"; }
