import { useState } from "react";
import { createAdminUser, createAdminVehicle, previewImport, publishImport, rollbackImport, updateAdminUser, updateAdminVehicle, updateAdminVehicleStatus } from "../api";
import { GlassButton, GlassCard, GlassInput } from "./glass";
import { notify } from "../state/feedback";

type Props = { tab: string };

export function AdminActionBar({ tab }: Props) {
  const [message, setMessage] = useState("");
  const [busy, setBusy] = useState(false);
  const [user, setUser] = useState({ id: "", version: "", username: "", password: "", role: "USER", status: "ACTIVE", realName: "", otherLongTermAccessEnabled: false, residentRemarksAccessEnabled: false, wechatWorkOrderAccessEnabled: false });
  const [vehicle, setVehicle] = useState({ id: "", version: "", plateNumber: "", category: "RESIDENT", vehicleType: "", status: "ACTIVE" });
  const [batch, setBatch] = useState("");
  const run = async (action: () => Promise<unknown>, success: string) => { setBusy(true); setMessage(""); try { await action(); setMessage(success); } catch (error) { const text = error instanceof Error ? error.message : "操作失败"; setMessage(text); notify("error", text); } finally { setBusy(false); } };
  if (tab === "账号管理") return <GlassCard className="admin-action-card"><h3>账号新增与权限修改</h3><div className="admin-form-grid"><GlassInput placeholder="账号" value={user.username} onChange={e => setUser({ ...user, username: e.target.value })} /><GlassInput placeholder="密码（新增时必填）" type="password" value={user.password} onChange={e => setUser({ ...user, password: e.target.value })} /><GlassInput placeholder="真实姓名" value={user.realName} onChange={e => setUser({ ...user, realName: e.target.value })} /><GlassInput placeholder="账号 ID（编辑时填写）" value={user.id} onChange={e => setUser({ ...user, id: e.target.value })} /><GlassInput placeholder="版本（编辑时填写）" value={user.version} onChange={e => setUser({ ...user, version: e.target.value })} /><select value={user.role} onChange={e => setUser({ ...user, role: e.target.value })}><option value="USER">普通用户</option><option value="ADMIN">管理员</option></select><select value={user.status} onChange={e => setUser({ ...user, status: e.target.value })}><option value="ACTIVE">启用</option><option value="DISABLED">停用</option></select></div><div className="permission-checks"><label><input type="checkbox" checked={user.otherLongTermAccessEnabled} onChange={e => setUser({ ...user, otherLongTermAccessEnabled: e.target.checked })} />其他长期车辆</label><label><input type="checkbox" checked={user.residentRemarksAccessEnabled} onChange={e => setUser({ ...user, residentRemarksAccessEnabled: e.target.checked })} />村民备注</label><label><input type="checkbox" checked={user.wechatWorkOrderAccessEnabled} onChange={e => setUser({ ...user, wechatWorkOrderAccessEnabled: e.target.checked })} />微信车单</label></div><div className="quick-actions"><GlassButton loading={busy} onClick={() => void run(() => createAdminUser({ username: user.username, password: user.password, role: user.role, realName: user.realName || null }), "账号已创建")}>新增账号</GlassButton><GlassButton loading={busy} tone="secondary" disabled={!user.id || !user.version} onClick={() => void run(() => updateAdminUser(Number(user.id), { username: user.username || null, password: user.password || null, role: user.role, status: user.status, realName: user.realName || null, otherLongTermAccessEnabled: user.otherLongTermAccessEnabled, residentRemarksAccessEnabled: user.residentRemarksAccessEnabled, wechatWorkOrderAccessEnabled: user.wechatWorkOrderAccessEnabled }, Number(user.version)), "账号权限已更新")}>保存编辑</GlassButton></div>{message && <p className="admin-form-message">{message}</p>}</GlassCard>;
  if (tab === "车辆档案") return <GlassCard className="admin-action-card"><h3>车辆新增、编辑与状态</h3><div className="admin-form-grid"><GlassInput placeholder="车牌号" value={vehicle.plateNumber} onChange={e => setVehicle({ ...vehicle, plateNumber: e.target.value })} /><GlassInput placeholder="车辆 ID（编辑时填写）" value={vehicle.id} onChange={e => setVehicle({ ...vehicle, id: e.target.value })} /><GlassInput placeholder="版本（编辑时填写）" value={vehicle.version} onChange={e => setVehicle({ ...vehicle, version: e.target.value })} /><GlassInput placeholder="车辆类型" value={vehicle.vehicleType} onChange={e => setVehicle({ ...vehicle, vehicleType: e.target.value })} /><select value={vehicle.category} onChange={e => setVehicle({ ...vehicle, category: e.target.value })}><option value="RESIDENT">村民车辆</option><option value="OTHER_LONG_TERM">其他长期车辆</option><option value="SCENIC_UNIT">驻景区单位</option><option value="CADRE">干部车辆</option></select><select value={vehicle.status} onChange={e => setVehicle({ ...vehicle, status: e.target.value })}><option value="ACTIVE">正常</option><option value="BLACKLISTED">拉黑</option><option value="STRICT_CHECK">严查</option><option value="INACTIVE">停用</option></select></div><div className="quick-actions"><GlassButton loading={busy} onClick={() => void run(() => createAdminVehicle({ plateNumber: vehicle.plateNumber, category: vehicle.category, vehicleType: vehicle.vehicleType || null, status: vehicle.status }), "车辆档案已创建")}>新增车辆</GlassButton><GlassButton loading={busy} tone="secondary" disabled={!vehicle.id || !vehicle.version} onClick={() => void run(() => updateAdminVehicle(Number(vehicle.id), { plateNumber: vehicle.plateNumber, category: vehicle.category, vehicleType: vehicle.vehicleType || null, status: vehicle.status }, Number(vehicle.version)), "车辆档案已更新")}>保存编辑</GlassButton><GlassButton loading={busy} tone="danger" disabled={!vehicle.id || !vehicle.version} onClick={() => void run(() => updateAdminVehicleStatus(Number(vehicle.id), vehicle.status, Number(vehicle.version)), "车辆状态已更新")}>更新状态</GlassButton></div>{message && <p className="admin-form-message">{message}</p>}</GlassCard>;
  if (tab === "导入中心") return <GlassCard className="admin-action-card"><h3>Excel 导入发布</h3><input type="file" accept=".xlsx,.xls" onChange={event => { const file = event.target.files?.[0]; if (file) void run(async () => { const result = await previewImport(file) as { id?: number }; if (result.id) setBatch(String(result.id)); return result; }, "预览批次已创建"); }} /><div className="admin-form-grid"><GlassInput placeholder="批次编号" value={batch} onChange={e => setBatch(e.target.value)} /></div><div className="quick-actions"><GlassButton loading={busy} disabled={!batch} onClick={() => void run(() => publishImport(Number(batch)), "导入批次已正式发布")}>正式发布</GlassButton><GlassButton loading={busy} disabled={!batch} tone="danger" onClick={() => void run(() => rollbackImport(Number(batch)), "导入批次已回滚")}>回滚批次</GlassButton></div>{message && <p className="admin-form-message">{message}</p>}</GlassCard>;
  return null;
}
